### ISSUE TITLE
Date slip with getNext() (again)

### ISSUE THREAD

**Issue by ThomasPerraudin** [poliander/cron#12]
Thank you for the v3.0.0. I don't know if it is linked to #9 and #11 but I still encounter a similar issue :

```
$c = new \Cron('0 3 * * *', new \DateTimeZone('Europe/Paris'));
echo $c->getNext();
```

___
### When run at 1649548801 //2022-04-10 02:00:01
Expected:

`1649552400 //2022-04-10 03:00:00`

Actual:

`1649552400 //2022-04-10 03:00:00` **OK**

___
### When run at 1649549102 //2022-04-10 02:05:02
Expected:

`1649552400 //2022-04-10 03:00:00`

Actual:

`1649638800 //2022-04-11 03:00:00` **ERROR**

**Comment by ThomasPerraudin** [comment]
I would like to help but I have difficulties to clearly understand your code. I guess that the issue may be in adjust() or forward().

**Comment by poliander** [comment]
I can partially explain what happens and confirm that the calculation routines you've mentioned are indeed working as expected. But there is still something odd regarding the timezone, the timestamp is not GMT what it should be, I will investigate this now.

Regarding your examples:

Your first example does work by accident, because: seconds are stripped away (e.g. the actual calculation start is 02:00:00), then by setting a GMT+1 timezone by constructor one hour is added (03:00:00), this matches the pattern and the result is as expected.

Your second example does not work because: GMT+1 timezone adds 1 hour, from this point in time (03:05:00) the next matching timestamp is 03:00:00 in the next day.

I suggest to not specify a timezone in the constructor because I see this as an edge case when using isMatching() method and obviously never thought this quite through when using it with getNext().

**Comment by poliander** [comment]
Oh, I think the calculation routine has indeed a problem.

**Comment by poliander** [comment]
Very nice find, please try v3.0.1 or v2.4.3 @ThomasPerraudin

**Comment by poliander** [comment]
I also added unit tests for your cases.

```
$expr = new CronExpression('0 3 * * *');
$ts = 1649549102;

echo date('c', $ts) . "\n";
echo date('c', $expr->getNext($ts)) . "\n";
```

Output:
```
2022-04-10T02:05:02+02:00
2022-04-10T03:00:00+02:00
```
