### ISSUE TITLE
if Cron('1 0 * * *'), 

### ISSUE THREAD

**Issue by marshhj** [poliander/cron#3]
if Cron('1 0 * * *'), getNext() will return next day  00:00:00 ?    why not  00:01:00  ???

**Comment by poliander** [comment]
Thank you very much for pointing this one out.

**Comment by poliander** [comment]
Fixed in version 1.2.1

**Comment by marshhj** [comment]
Thanks for fixing! But the bug still exists........

**Comment by poliander** [comment]
Strange, the unit test for your problem case tells otherwise... I'll look again into this today.

**Comment by poliander** [comment]
Okay, you're completely right - thank you again. The getNext() calculation was flawed when crossing month boundaries. I admit there should be more unit tests for that particular method.

The error should be fixed in current master branch. Would you be so kind and do a test? I also added another unit test for when "1 0 0 0 0" goes into next month.

**Comment by poliander** [comment]
Fixed in version 1.2.2
